title: Koki Ono
author: Koki Ono
email: ono-koki667[at]g.ecc.u-tokyo.ac.jp
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
header_pages:
  - index.md
  - publications.md
  - presentations.md
  - cv.md
  - ja/index.md
  - ja/publications.md
  - ja/presentations.md
  - ja/cv.md
