title: Koki Ono
author: Koki Ono / 大野 浩輝
email: ono-koki667[at]g.ecc.u-tokyo.ac.jp
googlescholar_username: phngeaEAAAAJ
orcid_username: 0009-0004-2198-6013
x_username: ono_k_

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - index.md
  - publications.md
  - presentations.md
  - cv.md
  - ja/index.md
  - ja/publications.md
  - ja/presentations.md
  - ja/cv.md
